#!/usr/bin/env bash
# fill_brew_formula.sh — replaces the placeholders in the Homebrew formula
# template (tools/release/brew.rb) with the REAL release values.
#
#   Usage:
#     tools/release/fill_brew_formula.sh [--version 0.1.0] [--platforms dist/SHA256SUMS] [--out dist/cerberus.rb]
#
#   If --platforms points to the SHA256SUMS generated by build_release.sh, the
#   three sums are taken from there automatically (macos-aarch64,
#   linux-x86_64, linux-aarch64). This way the formula is "ready to tap".
#
#   R9-4 rule: a missing sha for a REQUIRED platform is a hard error — the
#   script never emits a zero placeholder that could poison the tap.
#
#   In practice, in CI it is run for each platform before the release:
#     ./tools/release/build_release.sh 0.1.0                     # per os/arch
#     ./tools/release/fill_brew_formula.sh --version 0.1.0 --out dist/cerberus.rb

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

TPL="tools/release/brew.rb"
VERSION=""
PLATFORMS=""
OUT="dist/cerberus.rb"

while [ $# -gt 0 ]; do
  case "$1" in
    --version)    VERSION="$2"; shift 2 ;;
    --platforms)  PLATFORMS="$2"; shift 2 ;;
    --out)        OUT="$2"; shift 2 ;;
    --install)    OUT="contrib/homebrew/cerberus.rb"; shift ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
done

[ -n "$VERSION" ] || { echo "missing --version" >&2; exit 1; }
[ -f "$TPL" ] || { echo "template does not exist: $TPL" >&2; exit 1; }

# Extracts the sha256 from SHA256SUMS by exact substring match of the artifact name.
# R9-4: a missing sha for a required platform is a HARD ERROR (no zero
# placeholder may ever reach a published formula).
sha_for() {
  local needle="$1" h
  [ -n "$PLATFORMS" ] || { echo "error: --platforms is required (no zero placeholders allowed)" >&2; exit 1; }
  [ -f "$PLATFORMS" ] || { echo "error: $PLATFORMS does not exist" >&2; exit 1; }
  h="$(awk -v n="$needle" 'index($0, n) { print $1; exit }' "$PLATFORMS")"
  if [ -z "$h" ]; then
    echo "error: no sha256 for '$needle' in $PLATFORMS (R9-4: refusing to emit a placeholder)" >&2
    exit 1
  fi
  printf '%s\n' "$h"
}

MAC_ARM="$(sha_for "cerberus-${VERSION}-macos-aarch64.tar.gz")"
LIN_X64="$(sha_for "cerberus-${VERSION}-linux-x86_64.tar.gz")"
LIN_ARM="$(sha_for "cerberus-${VERSION}-linux-aarch64.tar.gz")"

mkdir -p "$(dirname "$OUT")"
sed -e "s/{{VERSION}}/$VERSION/g" \
    -e "s/{{SHA256_MACOS_AARCH64}}/$MAC_ARM/g" \
    -e "s/{{SHA256_LINUX_X86_64}}/$LIN_X64/g" \
    -e "s/{{SHA256_LINUX_AARCH64}}/$LIN_ARM/g" \
    "$TPL" > "$OUT"

echo "✔  Formula generated at $OUT"
echo "   version                  : $VERSION"
echo "   sha256 macos-aarch64     : ${MAC_ARM:0:16}…"
echo "   sha256 linux-x86_64      : ${LIN_X64:0:16}…"
echo "   sha256 linux-aarch64     : ${LIN_ARM:0:16}…"
echo "   Next steps:"
echo "   - ruby -c $OUT"
echo "   - brew audit --strict --new $OUT   (with real sha256 and published tag)"
echo "   - publish via brew tap (or GitHub release: gh release upload <tag> $OUT)"