//! Per-installation HMAC key for audit hashes (R9-16 / F5.2).
//!
//! **Design (smallest plan-compliant key source — no KMS, MVP only):**
//!
//! 1. `CERBERUS_HMAC_SECRET` env (non-empty) wins — explicit override for
//!    operation/tests; never a silent default (fix-plan F5.2).
//! 2. Otherwise the key file `<config_dir>/audit-hmac-key` — 64 lowercase
//!    hex chars (32 bytes) generated by CSPRNG on first boot and persisted
//!    atomically with `0600` permissions on unix (on Windows the file lives
//!    inside the user profile, which carries the default ACL protection).
//! 3. If the file is missing/corrupt/unwritable the daemon generates a fresh
//!    key (persisting when possible); the CLI dry-run path
//!    ([`resolve_existing_or_ephemeral_key`]) never writes and falls back to
//!    an ephemeral per-process CSPRNG key.
//!
//! There is NO unkeyed fallback: every hash of secret material in the
//! product is keyed HMAC-SHA256. Consequence documented in the F5 evidence
//! pack: an ephemeral key makes dry-run hashes non-comparable across runs
//! (display-only), and a regenerated key breaks dedup correlation with
//! events hashed under the previous key (old rows keep their legacy
//! `sha256:`/`hmac:` digests — never re-hashed, raw values were discarded
//! by design).
//!
//! Key lifecycle: rotation = replace the file or set the env override;
//! rotation invalidates cross-key hash correlation going forward (documented
//! dedup change). The key is never logged, never `Debug`-printed, and never
//! leaves the process.

use std::fs;
use std::path::Path;

use crate::platform;

/// File name of the persisted installation key (inside `config_dir`).
pub(crate) const KEY_FILE_NAME: &str = "audit-hmac-key";

/// Length of the generated key in bytes (256-bit HMAC-SHA256 key).
const KEY_BYTES: usize = 32;

/// Where the resolved key came from (for the boot log — never the key).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum KeySource {
    /// `CERBERUS_HMAC_SECRET` environment override.
    Env,
    /// Existing persisted key file.
    File,
    /// Freshly generated (and persisted when possible) this boot.
    Generated,
    /// Freshly generated this boot because the persisted file was CORRUPT —
    /// repair succeeded (F5 F-2: this must be loud, it is NOT a first boot:
    /// dedup correlation with events hashed under the previous key is lost
    /// at this boundary).
    Regenerated,
    /// Per-process ephemeral CSPRNG key (no filesystem available/wanted).
    Ephemeral,
}

impl KeySource {
    /// Human-readable source label for the boot log (never contains the key).
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::Env => "env override (CERBERUS_HMAC_SECRET)",
            Self::File => "persisted key file",
            Self::Generated => "generated + persisted this boot",
            Self::Regenerated => "regenerated this boot (key file was corrupt — correlation with prior hashes lost)",
            Self::Ephemeral => "ephemeral (per-process, not persisted)",
        }
    }

    /// F5 F-3: which sources need the loud WARN in addition to the boot
    /// label? A fresh generation, a corruption-repair regeneration and the
    /// ephemeral fallback all change how the hashes must be interpreted
    /// (correlation breakage / non-comparability) and must never pass as a
    /// routine boot.
    pub(crate) const fn requires_loud_warning(self) -> bool {
        matches!(self, Self::Generated | Self::Regenerated | Self::Ephemeral)
    }
}

/// Resolve (or create) the installation audit key for the daemon.
///
/// Precedence: env override → persisted key file → generate + persist.
/// A CORRUPT key file (F5 F-2) is distinguished from an absent one: the
/// regeneration is reported as [`KeySource::Regenerated`] so the boot can
/// announce the dedup-correlation breakage loudly instead of looking like a
/// first boot. Only fails to persist when the filesystem refuses; even then
/// a valid CSPRNG key is returned (with [`KeySource::Generated`] downgraded
/// to ephemeral semantics for that boot).
pub(crate) fn resolve_or_create_key(config_dir: &Path) -> (Vec<u8>, KeySource) {
    if let Some(key) = key_from_env() {
        return (key, KeySource::Env);
    }
    match key_file_status(config_dir) {
        KeyFileStatus::Valid(key) => (key, KeySource::File),
        // Absent → first boot: generate + persist.
        KeyFileStatus::Missing => generate_and_persist(config_dir).map_or_else(
            || (ephemeral_key(), KeySource::Ephemeral),
            |key| (key, KeySource::Generated),
        ),
        // Corrupt → repair by regeneration; LOUD (F5 F-2), never silent: the
        // source label explicitly names the corruption and the correlation
        // loss, and `requires_loud_warning` makes the daemon WARN.
        KeyFileStatus::Corrupt => generate_and_persist(config_dir).map_or_else(
            || (ephemeral_key(), KeySource::Ephemeral),
            |key| (key, KeySource::Regenerated),
        ),
    }
}

/// Resolve the key WITHOUT side effects (CLI dry-run: `cerberus scan/test`).
///
/// Precedence: env override → persisted key file → ephemeral per-process
/// CSPRNG key. Dry-run hashes under an ephemeral key are display-only and
/// not comparable across runs (documented consequence of never writing from
/// a read-only diagnostic).
pub(crate) fn resolve_existing_or_ephemeral_key(config_dir: &Path) -> (Vec<u8>, KeySource) {
    if let Some(key) = key_from_env() {
        return (key, KeySource::Env);
    }
    key_from_file(config_dir).map_or_else(|| (ephemeral_key(), KeySource::Ephemeral), |key| (key, KeySource::File))
}

/// The daemon's config dir (delegated to `platform` for cross-platform paths).
pub(crate) fn default_config_dir() -> std::path::PathBuf {
    platform::config_dir()
}

/// Non-empty `CERBERUS_HMAC_SECRET` bytes (explicit override).
fn key_from_env() -> Option<Vec<u8>> {
    std::env::var("CERBERUS_HMAC_SECRET")
        .ok()
        .filter(|s| !s.is_empty())
        .map(String::into_bytes)
}

/// Read + validate the persisted key file; `None` when absent or malformed.
fn key_from_file(config_dir: &Path) -> Option<Vec<u8>> {
    match key_file_status(config_dir) {
        KeyFileStatus::Valid(key) => Some(key),
        KeyFileStatus::Missing | KeyFileStatus::Corrupt => None,
    }
}

/// Status of the persisted key file: distinguishes ABSENT (first boot) from
/// CORRUPT (F5 F-2 — the repair must be loud, the correlation with previous
/// hashes is lost) from VALID.
enum KeyFileStatus {
    Valid(Vec<u8>),
    Missing,
    Corrupt,
}

/// Read + validate the persisted key file with the corrupt/absent split.
fn key_file_status(config_dir: &Path) -> KeyFileStatus {
    fs::read_to_string(config_dir.join(KEY_FILE_NAME)).map_or(KeyFileStatus::Missing, |raw| {
        let hex_str = raw.trim();
        if hex_str.len() == KEY_BYTES * 2 && hex_str.bytes().all(|b| b.is_ascii_hexdigit()) {
            decode_hex(hex_str).map_or(KeyFileStatus::Corrupt, KeyFileStatus::Valid)
        } else {
            KeyFileStatus::Corrupt
        }
    })
}

/// Generate a 256-bit CSPRNG key and persist it (hex, `0600` on unix,
/// atomic tmp+rename). Returns `None` when persistence failed — the caller
/// falls back to an ephemeral key (never to an unkeyed hash).
///
/// F5 F-1 (creation-time umask race): the tmp file is created with
/// `OpenOptions::create_new(true).mode(0o600)` — the restrictive mode is
/// applied AT CREATION, so there is no window where the key hex sits at a
/// umask-derived 0644/0666 before the chmod, and a failed chmod cannot leave
/// a world-readable key behind (creation itself fails instead). Every
/// `Result` is handled: a persistence failure degrades to the ephemeral
/// fallback (loud), never to an insecure file.
fn generate_and_persist(config_dir: &Path) -> Option<Vec<u8>> {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let key = ephemeral_key();
    let mut hex_str = String::with_capacity(KEY_BYTES * 2);
    for b in &key {
        hex_str.push(HEX[usize::from(b >> 4)] as char);
        hex_str.push(HEX[usize::from(b & 0x0f)] as char);
    }
    fs::create_dir_all(config_dir).ok()?;
    let target = config_dir.join(KEY_FILE_NAME);
    let tmp = config_dir.join(format!("{KEY_FILE_NAME}.tmp-{}", std::process::id()));
    // Remove a stale tmp from a previous crashed boot BEFORE create_new:
    // `create_new` fails if the path exists, and reusing a stale tmp (whose
    // content we would overwrite anyway) must never fail the boot.
    let _ = fs::remove_file(&tmp);
    let write = open_key_tmp_0600(&tmp).and_then(|mut f| {
        use std::io::Write;
        f.write_all(format!("{hex_str}\n").as_bytes())
    });
    if write.is_err() {
        let _ = fs::remove_file(&tmp);
        return None;
    }
    fs::rename(&tmp, &target)
        .map_err(|_| {
            let _ = fs::remove_file(&tmp);
        })
        .ok()?;
    Some(key)
}

/// Create the tmp key file EXCLUSIVELY (`create_new`) with `0600` applied at
/// creation on unix — the umask can only clear bits the mode already clears,
/// so there is no window where the key hex is group/world-readable (F5 F-1).
#[cfg(unix)]
fn open_key_tmp_0600(path: &Path) -> std::io::Result<std::fs::File> {
    use std::os::unix::fs::OpenOptionsExt;
    std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)
}

/// Non-unix fallback: exclusive creation; the file lives inside the user
/// profile, which carries the default ACL protection (documented).
#[cfg(not(unix))]
fn open_key_tmp_0600(path: &Path) -> std::io::Result<std::fs::File> {
    std::fs::OpenOptions::new().write(true).create_new(true).open(path)
}

/// 256-bit CSPRNG key (`getrandom`, the same source the vault and
/// break-glass nonces use).
fn ephemeral_key() -> Vec<u8> {
    let mut bytes = [0u8; KEY_BYTES];
    getrandom::getrandom(&mut bytes).expect("CSPRNG unavailable");
    bytes.to_vec()
}

/// Decode an even-length lowercase/uppercase hex string.
fn decode_hex(s: &str) -> Option<Vec<u8>> {
    let bytes = s.as_bytes();
    if !bytes.len().is_multiple_of(2) {
        return None;
    }
    let pair = |hi: u8, lo: u8| -> Option<u8> {
        let v = |c: u8| -> Option<u8> {
            match c {
                b'0'..=b'9' => Some(c - b'0'),
                b'a'..=b'f' => Some(c - b'a' + 10),
                b'A'..=b'F' => Some(c - b'A' + 10),
                _ => None,
            }
        };
        Some((v(hi)? << 4) | v(lo)?)
    };
    bytes.chunks(2).map(|c| pair(c[0], c[1])).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Serialize tests that mutate `CERBERUS_HMAC_SECRET` (process-global).
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn temp_dir(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "cerberus_audit_key_{name}_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map_or(0, |d| d.as_nanos())
        ));
        fs::create_dir_all(&dir).expect("temp dir");
        dir
    }

    fn clear_env() {
        std::env::remove_var("CERBERUS_HMAC_SECRET");
    }

    #[test]
    fn env_override_wins_over_everything() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let dir = temp_dir("env_wins");
        std::env::set_var("CERBERUS_HMAC_SECRET", "explicit-override");
        let (key, source) = resolve_or_create_key(&dir);
        assert_eq!(source, KeySource::Env);
        assert_eq!(key, b"explicit-override".to_vec());
        // Even an existing valid file must NOT win over the env.
        let (key2, source2) = resolve_or_create_key(&dir);
        assert_eq!(source2, KeySource::Env);
        assert_eq!(key2, key);
        clear_env();
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn generates_and_persists_0600_key_then_reuses_it() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let dir = temp_dir("generate");
        let (key, source) = resolve_or_create_key(&dir);
        assert_eq!(source, KeySource::Generated);
        assert_eq!(key.len(), KEY_BYTES, "256-bit key");

        let path = dir.join(KEY_FILE_NAME);
        assert!(path.exists(), "key file persisted");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&path).expect("meta").permissions().mode();
            assert_eq!(mode & 0o777, 0o600, "key file must be 0600, got {mode:o}");
        }

        // Second boot reuses the SAME key (determinism across restarts).
        let (key2, source2) = resolve_or_create_key(&dir);
        assert_eq!(source2, KeySource::File);
        assert_eq!(key2, key, "persisted key must be reused");

        // The persisted file never contains the raw key in binary form
        // (hex only) and the raw key bytes never appear in the file.
        let raw = fs::read_to_string(&path).expect("read");
        assert_eq!(raw.trim().len(), 64, "file is 64 hex chars");
        assert!(!raw.contains('\0'));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn malformed_key_file_is_replaced_with_a_fresh_key() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let dir = temp_dir("malformed");
        fs::write(dir.join(KEY_FILE_NAME), "not-a-valid-hex-key!!").expect("write garbage");
        let (key, source) = resolve_or_create_key(&dir);
        // F5 F-2: a CORRUPT file is NOT a first boot — the source says
        // "regenerated" so the boot line can announce the correlation loss.
        assert_eq!(
            source,
            KeySource::Regenerated,
            "corrupt file → fresh key, labeled as repair"
        );
        assert!(
            source.requires_loud_warning(),
            "corruption repair must be loud (F5 F-2/F-3)"
        );
        assert_eq!(key.len(), KEY_BYTES);
        // The file is repaired for the next boot.
        let (key2, source2) = resolve_or_create_key(&dir);
        assert_eq!(source2, KeySource::File);
        assert_eq!(key2, key);
        fs::remove_dir_all(&dir).ok();
    }

    /// F5 F-1: the key tmp file is created with `0600` AT CREATION
    /// (`create_new` + mode), so there is no umask-dependent window where
    /// the key hex is group/world-readable — the pre-fix `fs::write` +
    /// post-chmod sequence had a 0644/0666 window (empirically reproduced by
    /// the F5 security panel, umask probe cmd 28). Here we verify the final
    /// mode AND the exclusive-creation semantics (a pre-existing path fails
    /// creation instead of being truncated at a wrong mode).
    #[test]
    fn key_tmp_is_created_exclusively_with_0600() {
        let dir = temp_dir("create_new_mode");
        let path = dir.join("probe-key");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let f = open_key_tmp_0600(&path).expect("create_new at 0600");
            drop(f);
            let mode = fs::metadata(&path).expect("meta").permissions().mode();
            assert_eq!(mode & 0o777, 0o600, "created mode must be 0600, got {mode:o}");
            // create_new semantics: a second open on the same path fails.
            assert!(
                open_key_tmp_0600(&path).is_err(),
                "create_new must not truncate an existing file"
            );
        }
        #[cfg(not(unix))]
        {
            let f = open_key_tmp_0600(&path).expect("exclusive create");
            drop(f);
            assert!(
                open_key_tmp_0600(&path).is_err(),
                "create_new must not truncate an existing file"
            );
        }
        fs::remove_dir_all(&dir).ok();
    }

    /// F5 F-1: a STALE tmp file from a crashed previous boot does not break
    /// the boot (it is removed before the exclusive creation).
    #[test]
    fn stale_tmp_file_does_not_block_key_generation() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let dir = temp_dir("stale-tmp");
        // A crashed boot left a world-readable tmp behind.
        fs::write(dir.join(format!("{KEY_FILE_NAME}.tmp-{}", std::process::id())), "stale").expect("stale tmp");
        let (key, source) = resolve_or_create_key(&dir);
        assert_eq!(key.len(), KEY_BYTES);
        assert!(matches!(source, KeySource::Generated | KeySource::Regenerated));
        let path = dir.join(KEY_FILE_NAME);
        assert!(path.exists(), "key persisted despite the stale tmp");
        // The stale tmp is gone (removed before create_new, or renamed over).
        assert!(
            !dir.join(format!("{KEY_FILE_NAME}.tmp-{}", std::process::id())).exists(),
            "no tmp residue"
        );
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn loud_warning_matrix() {
        // F5 F-3: which sources WARN. Env and a normal File boot are routine;
        // Generated/Regenerated/Ephemeral change the hash semantics and are
        // loud.
        assert!(!KeySource::Env.requires_loud_warning());
        assert!(!KeySource::File.requires_loud_warning());
        assert!(KeySource::Generated.requires_loud_warning());
        assert!(KeySource::Regenerated.requires_loud_warning());
        assert!(KeySource::Ephemeral.requires_loud_warning());
    }

    #[test]
    fn read_only_resolution_never_writes_and_falls_back_ephemeral() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let dir = temp_dir("readonly");
        let (key, source) = resolve_existing_or_ephemeral_key(&dir);
        assert_eq!(source, KeySource::Ephemeral, "no env, no file → ephemeral");
        assert_eq!(key.len(), KEY_BYTES);
        assert!(
            !dir.join(KEY_FILE_NAME).exists(),
            "dry-run must never write the key file"
        );

        // Different invocations get different ephemeral keys (CSPRNG), but
        // env/file paths stay stable.
        let (key2, _) = resolve_existing_or_ephemeral_key(&dir);
        assert_ne!(key, key2, "ephemeral keys are per-process CSPRNG");
        std::env::set_var("CERBERUS_HMAC_SECRET", "stable");
        let (key3, source3) = resolve_existing_or_ephemeral_key(&dir);
        assert_eq!(source3, KeySource::Env);
        assert_eq!(key3, b"stable".to_vec());
        clear_env();
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn decode_hex_roundtrip() {
        assert_eq!(decode_hex("00ff10"), Some(vec![0x00, 0xff, 0x10]));
        assert_eq!(decode_hex("abc"), None);
        assert_eq!(decode_hex("zz"), None);
        let hex32: String = "ab".repeat(32);
        assert_eq!(decode_hex(&hex32).map(|v| v.len()), Some(32));
    }
}
