//! Cerberus Local — sensitive-data firewall for LLM agents.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::sync::{Arc, RwLock};
use std::time::Duration;

use cerberus_engine::engine::{CompiledEngine, EngineBuilder};
use cerberus_engine::loader::load_rules_from_str;
use cerberus_packs::license::LicenseManager;
use cerberus_packs::updater::{PackManager, PackTrustRoot};
use cerberus_packs::wire::{ControlPlaneEndpoint, ENDPOINT_FILE};
use cerberus_proxy::api::ApiContext;
use cerberus_proxy::config::{OperationMode, ProxyConfig, UpstreamConfig};
use cerberus_proxy::forward::spawn_forward_proxy;
use cerberus_proxy::proxy::{spawn_managed_proxy, ProxyContext};
use cerberus_store::store::AuditStore;

use crate::packs::default_rules_json;
use crate::platform;

/// Path to the PID file.
pub(crate) fn pid_path() -> PathBuf {
    config_dir().join("cerberus.pid")
}

fn endpoint_path() -> PathBuf {
    config_dir().join(ENDPOINT_FILE)
}

fn persist_endpoint(actual: std::net::SocketAddr, pid: u32) -> Result<(), String> {
    let endpoint = ControlPlaneEndpoint::new(&actual.to_string(), pid).map_err(|e| e.to_string())?;
    let target = endpoint_path();
    let tmp = target.with_extension(format!("json.tmp-{pid}"));
    fs::write(&tmp, endpoint.to_json().map_err(|e| e.to_string())?)
        .map_err(|e| format!("cannot write endpoint metadata: {e}"))?;
    if let Err(first) = fs::rename(&tmp, &target) {
        // Windows does not replace an existing target with rename. A stale
        // descriptor is not authoritative (the PID file is), so it is removed
        // and retried with the temp fully written.
        if target.exists() {
            fs::remove_file(&target).map_err(|e| format!("cannot replace stale endpoint metadata: {e}"))?;
            fs::rename(&tmp, &target).map_err(|e| format!("cannot publish endpoint metadata: {e}"))?;
        } else {
            let _ = fs::remove_file(&tmp);
            return Err(format!("cannot publish endpoint metadata: {first}"));
        }
    }
    Ok(())
}

fn remove_runtime_files() {
    let _ = fs::remove_file(pid_path());
    let _ = fs::remove_file(endpoint_path());
}

/// Path to the configuration directory (delegated to `platform` so that on
/// Windows it is `%APPDATA%\Cerberus` instead of `~\.cerberus`).
pub(crate) fn config_dir() -> std::path::PathBuf {
    platform::config_dir()
}

/// Path to the YAML config file generated by `cerberus init`.
fn config_file() -> PathBuf {
    config_dir().join("config.yaml")
}

/// Path to the installed rule packs directory (`~/.cerberus/packs`).
pub(crate) fn packs_dir() -> PathBuf {
    config_dir().join("packs")
}

/// Path to the active license file: env `CERBERUS_LICENSE_PATH` or, by
/// default, `~/.cerberus/license.json`.
pub(crate) fn license_path() -> PathBuf {
    std::env::var("CERBERUS_LICENSE_PATH")
        .ok()
        .filter(|p| !p.is_empty())
        .map_or_else(|| config_dir().join("license.json"), PathBuf::from)
}

/// Load the active license for the daemon (F7 connection in the product,
/// fix from code review item 12).
///
/// **Product fail-open policy**: if the file does not exist or verification
/// fails (no trust root or invalid signature), it continues with Free tier
/// and logs a clear warning. The license only gates Pro features (open-core:
/// the engine and the basic local mode remain free, §7 of the plan).
pub(crate) fn load_license(path: Option<&std::path::Path>) -> LicenseManager {
    let Some(path) = path else {
        return LicenseManager::free();
    };
    if !path.exists() {
        return LicenseManager::free();
    }
    match LicenseManager::from_file(path) {
        Ok(mgr) => mgr,
        Err(e) => {
            tracing::warn!(
                "license load failed ({e}); continuing with Free tier (fail-open) — set \
                 CERBERUS_LICENSE_PUBLIC_KEY and a valid license at CERBERUS_LICENSE_PATH"
            );
            LicenseManager::free()
        }
    }
}

/// License summary for the boot log, with the machine-readable
/// `tier=pro|free` field (key for the integration test).
#[must_use]
pub(crate) fn license_summary(mgr: &LicenseManager) -> String {
    let tier = if mgr.is_pro() { "pro" } else { "free" };
    let state = if mgr.is_expired() { "expired" } else { "valid" };
    format!("tier={tier} state={state}\n{}", mgr.report())
}

/// Try to load YAML config from `cerberus init`.
/// Returns `None` if the file does not exist or is invalid.
fn load_proxy_config() -> Option<ProxyConfig> {
    load_proxy_config_from(&config_file())
}

/// Load config from an explicit path to isolate the filesystem in tests.
///
/// Fix P3-1 (attempt 2): a config file that EXISTS but fails to parse is
/// never silently swallowed — the real serde error is logged loudly (the
/// operator previously saw the misleading `no upstreams configured` instead).
/// The behavior stays fail-closed: the invalid file is ignored and the
/// defaults apply (or boot refuses where required).
fn load_proxy_config_from(path: &std::path::Path) -> Option<ProxyConfig> {
    if !path.exists() {
        return None;
    }
    match ProxyConfig::from_file(path) {
        Ok(cfg) => Some(cfg),
        Err(e) => {
            tracing::error!(
                "proxy config file {} is INVALID and will be IGNORED (fail-closed defaults apply — fix the parse error or remove the file): {e}",
                path.display()
            );
            None
        }
    }
}

/// Resolve the per-installation audit-hash key (R9-16, F5.2).
///
/// Precedence: `CERBERUS_HMAC_SECRET` env override → persisted key file →
/// generate + persist (0600, atomic). There is NO unkeyed fallback: every
/// hash of secret material in the product is keyed HMAC-SHA256. See
/// `audit_key.rs` for the full key-management design.
pub(crate) fn resolve_audit_key() -> (Vec<u8>, crate::audit_key::KeySource) {
    crate::audit_key::resolve_or_create_key(&crate::audit_key::default_config_dir())
}

/// Non-empty env value as `Option<String>`.
fn env_nonempty(name: &str) -> Option<String> {
    std::env::var(name).ok().filter(|s| !s.is_empty())
}

/// Audit retention days: env `CERBERUS_RETENTION_DAYS` (default 90). `0` =
/// minimum retention (see `store::purge_old`).
fn retention_days_from_env() -> u64 {
    std::env::var("CERBERUS_RETENTION_DAYS")
        .ok()
        .and_then(|s| s.trim().parse::<u64>().ok())
        .unwrap_or(90)
}

/// Compile the base engine (default rules + the installation payload-hash
/// key — ALWAYS keyed, R9-16/F5.2).
/// This is the ONLY source of rules for the daemon and the CLI: from here
/// derives both the `PackManager` (which merges it with the packs, finding 7)
/// and the snapshot the proxy receives — without a second independent
/// compilation.
///
/// # Errors
///
/// Returns the error from loading/compiling the rules.
fn build_base_engine(audit_key: &[u8]) -> Result<cerberus_engine::engine::CompiledEngine, String> {
    let rules_json = default_rules_json();
    let rules = load_rules_from_str(&rules_json).map_err(|e| format!("error loading rules: {e}"))?;
    EngineBuilder::new(&rules)
        .with_payload_secret(audit_key.to_vec())
        .build()
        .map_err(|e| format!("engine build error: {e}"))
}

/// Open a `PackManager` over `packs_dir()` with the base engine — the SAME
/// for the daemon and the CLI (finding 7: there is no second engine).
///
/// # Errors
///
/// Returns an error if the packs directory cannot be created or compilation fails.
fn open_packs_manager(audit_key: &[u8]) -> Result<PackManager, String> {
    let engine = build_base_engine(audit_key)?;
    let license = load_license(Some(&license_path()));
    let trust_root =
        PackTrustRoot::from_optional_key(env_nonempty("CERBERUS_PACK_TRUST_ROOT")).gated_by_pro(license.is_pro());
    PackManager::open(packs_dir(), engine, &trust_root).map_err(|e| format!("packs setup error: {e}"))
}

// ─────────────────────────────────────────────────────────────────────────────
// A) Real MERGE of the config: base = config.yaml (fail_policy, max_body_bytes,
//    health_path, log_level, etc. ALL preserved — see the fix from code review
//    v4 finding 5, daemon part: previously it was reconstructed with
//    `..default()` and those YAML fields were lost).
//
// Precedence:
//   listen      env `CERBERUS_LISTEN_HOST` (or host from file_cfg) + CLI port.
//   upstreams   env `CERBERUS_UPSTREAMS` (JSON) > env `CERBERUS_UPSTREAM_URL`
//               (openai/anthropic/default) > config.yaml > instructive error.
//   admin_token env `CERBERUS_ADMIN_TOKEN` > config.yaml.
//   mode        env `CERBERUS_MODE` > config.yaml.
// ─────────────────────────────────────────────────────────────────────────────
fn resolve_config(port: u16, file_cfg: Option<ProxyConfig>) -> Result<ProxyConfig, String> {
    let mut config = file_cfg.unwrap_or_default();

    // Mode: env > file.
    if let Some(mode_raw) = env_nonempty("CERBERUS_MODE") {
        config.mode = serde_yaml::from_str::<OperationMode>(&mode_raw)
            .or_else(|_| serde_json::from_str::<OperationMode>(&mode_raw))
            .map_err(|e| format!("invalid CERBERUS_MODE ('{mode_raw}'): {e}"))?;
    }

    // Listen: host from env (0.0.0.0 in Docker) or the file's host; the
    // port is ALWAYS the CLI's (default 8787).
    let listen_host = std::env::var("CERBERUS_LISTEN_HOST")
        .ok()
        .filter(|h| !h.is_empty())
        .unwrap_or_else(|| {
            config
                .listen
                .split(':')
                .next()
                .map(str::to_string)
                .filter(|h| !h.is_empty())
                .unwrap_or_else(|| "127.0.0.1".to_string())
        });
    config.listen = format!("{listen_host}:{port}");

    // Upstreams: env (JSON) > env URL (openai/anthropic/default) > file.
    // With no upstream → error with clear instructions.
    let upstream_auth = "authorization".to_string();
    if let Some(upstreams_json) = env_nonempty("CERBERUS_UPSTREAMS") {
        config.upstreams = serde_json::from_str::<HashMap<String, UpstreamConfig>>(&upstreams_json)
            .map_err(|e| format!("invalid CERBERUS_UPSTREAMS JSON: {e}"))?;
    } else if let Some(url) = env_nonempty("CERBERUS_UPSTREAM_URL") {
        // P1 #7 compat: the base URL creates MULTIPLE upstreams so that
        // prefix-based routing works (openai/anthropic/default).
        let mut m = HashMap::new();
        m.insert(
            "openai".to_string(),
            UpstreamConfig {
                url: url.clone(),
                path_prefix: Some("/openai/".to_string()),
                auth_header: upstream_auth.clone(),
                mode: None,
                expected_auth: None,
            },
        );
        m.insert(
            "anthropic".to_string(),
            UpstreamConfig {
                url: url.clone(),
                path_prefix: Some("/anthropic/".to_string()),
                auth_header: upstream_auth.clone(),
                mode: None,
                expected_auth: None,
            },
        );
        m.insert(
            "default".to_string(),
            UpstreamConfig {
                url,
                path_prefix: None,
                auth_header: upstream_auth,
                mode: None,
                expected_auth: None,
            },
        );
        config.upstreams = m;
    }

    if config.upstreams.is_empty() {
        return Err("no upstreams configured: run 'cerberus init' or export CERBERUS_UPSTREAM_URL".to_string());
    }

    // Admin token: env takes priority, then config.yaml (control plane P0).
    if let Some(token) = env_nonempty("CERBERUS_ADMIN_TOKEN") {
        config.admin_token = Some(token);
    }

    Ok(config)
}

#[allow(
    clippy::too_many_lines,
    clippy::option_if_let_else,
    clippy::map_unwrap_or,
    clippy::if_not_else
)]
pub(crate) async fn start(port: u16, chain: Option<String>) -> Result<String, String> {
    // Check if already running
    if is_running() {
        return Err("Cerberus is already running. Use 'cerberus stop' first.".to_string());
    }

    // R9-16 (F5.2): resolve the per-installation audit-hash key ONCE per
    // boot and thread it through EVERY engine construction + the API context,
    // so all secret-material hashes (event hashes, entropy, break-glass
    // reasons) share one keyed, domain-separated scheme.
    let (audit_key, key_source) = resolve_audit_key();
    println!("audit hashing: keyed HMAC-SHA256 (key source: {})", key_source.label());

    // UNIQUE base engine (finding 7): used by PackManager and, after the
    // initial pack load, by the snapshot the proxy receives.
    let base_engine = build_base_engine(&audit_key)?;

    // A) Real config: base = config.yaml (without losing fields) + overrides.
    let file_cfg = load_proxy_config();
    let mut config = resolve_config(port, file_cfg)?;

    // --chain: rewrite all upstreams to forward to another local proxy
    // (e.g. headroom) instead of the provider directly. This lets you
    // stack Cerberus (DLP) → headroom (compression) → provider.
    if let Some(ref chain_url) = chain {
        let chain_url = chain_url.trim_end_matches('/');
        for up in config.upstreams.values_mut() {
            up.url = chain_url.to_string();
        }
        println!("chain: all upstreams → {chain_url}");
    }
    // A missing/disabled `mitm.json` produces `None`: the reverse proxy
    // remains always the default. If the user explicitly opted into MITM, we
    // validate CA/hosts/listener before initializing the daemon.
    let mitm_config = crate::mitm::runtime_config()?;

    // C/F) Audit with configurable retention (env, default 90 days).
    let retention_days = retention_days_from_env();
    let db_path = pid_path()
        .parent()
        .map_or_else(|| PathBuf::from("/tmp/cerberus/cerberus.db"), |p| p.join("cerberus.db"));
    fs::create_dir_all(config_dir()).map_err(|e| format!("cannot create config dir: {e}"))?;

    let store_opt = AuditStore::open_with(&db_path, retention_days).map(Arc::new).ok();
    if store_opt.is_some() {
        println!(
            "Audit store opened at {} (retention {retention_days} days)",
            db_path.display()
        );
    } else {
        eprintln!("warning: audit store unavailable — events will be in-memory only");
    }

    println!(
        "effective config: mode={} fail_policy={} max_body_bytes={} health_path={}",
        format!("{:?}", config.mode).to_lowercase(),
        format!("{:?}", config.fail_policy).to_lowercase(),
        config.max_body_bytes.unwrap_or(0),
        config.health_path
    );

    // Shared config proxy ↔ Config API (real hot-reload, P0-5).
    let shared_config = Arc::new(std::sync::RwLock::new(config.clone()));

    // F7: active license (fail-open → Free if not verifiable).
    let boot_license_path = license_path();
    let license: Arc<LicenseManager> = Arc::new(load_license(Some(boot_license_path.as_path())));
    tracing::info!(
        "license: loaded from {} —\n{}",
        boot_license_path.display(),
        license_summary(&license)
    );

    // F7: PackManager over the SAME base engine; we load signed packs already
    // present in `~/.cerberus/packs` (if there is a trust root) BEFORE raising
    // the proxy → the snapshot the proxy receives already includes those packs.
    // F7: PackManager with the SAME base engine. Packs in the dir are hydrated
    // BEFORE raising the proxy (trust root); the initial snapshot feeds the
    // proxy's engine. Runtime hot-reload is managed by a packs WORKER
    // (fix review v5): a shared `Arc<RwLock<Arc<CompiledEngine>>>` with the
    // proxy is atomically swapped on each install/rollback via the
    // `/api/packs/*` routes.
    // The trust root is resolved AFTER the license and disabled in Free tier
    // before constructing the manager. This way no active manifest can
    // hydrate Pro packs during the constructor and evade the boot gate.
    let trust_root =
        PackTrustRoot::from_optional_key(env_nonempty("CERBERUS_PACK_TRUST_ROOT")).gated_by_pro(license.is_pro());
    let packs_manager =
        PackManager::open(packs_dir(), base_engine, &trust_root).map_err(|e| format!("packs setup error: {e}"))?;
    if !trust_root.is_enabled() {
        tracing::warn!("packs: no effective trust root (Free tier or root missing) — base engine, zero packs");
    }
    let engine_for_proxy = packs_manager.snapshot_engine(Some(&audit_key)).await?;
    let installed = packs_manager.list_packs().await.len();
    println!(
        "packs: manager ready at {} ({} packs installed; snapshot passes to the proxy)",
        packs_dir().display(),
        installed
    );

    // Fix review v6.1: the BASE rules of the dataplane are the packs snapshot
    // (defaults + signed packs). The policy persisted in config.yaml
    // (categories, overrides, and custom rules) is applied ON TOP at boot →
    // what the operator saved from the dashboard is restored without having
    // to reinstall anything. If the YAML brings a policy that does not
    // compile, boot fails loudly: we prefer not to boot over booting with
    // less detection than the operator believes they have.
    let base_rules: Vec<cerberus_engine::rule::Rule> = engine_for_proxy.rules().to_vec();
    config
        .policy
        .validate()
        .map_err(|e| format!("invalid policy in {}: {e}", config_file().display()))?;
    let boot_engine = cerberus_proxy::detection_policy::build_engine(&base_rules, &config.policy, Some(&audit_key))
        .map_err(|e| format!("policy engine build error: {e}"))?;
    println!(
        "policy: {} categories, {} overrides, {} custom rules, {} allowlist entries → engine with {} rules ({} base)",
        config.policy.categories.len(),
        config.policy.rule_actions.len(),
        config.policy.custom_rules.len(),
        config.policy.allowlist.len(),
        boot_engine.num_rules(),
        base_rules.len(),
    );

    // Swappable engine (hot-reload): the proxy reads from here; the packs
    // worker writes the snapshot after install/rollback and the control plane
    // republishes after each policy change.
    let live_engine: Arc<RwLock<Arc<CompiledEngine>>> = Arc::new(std::sync::RwLock::new(Arc::new(boot_engine)));
    let engine_control =
        cerberus_proxy::detection_policy::EngineControl::new(live_engine.clone(), base_rules, Some(audit_key.clone()));

    // Rule packs worker (async) — runs install/rollback/list against the
    // PackManager and, after each mutation, replaces the BASE rules and
    // republishes the policy on top → the running proxy changes rules WITHOUT
    // restarting and without losing the operator's custom rules.
    let pack_worker_manager: Arc<PackManager> = Arc::new(packs_manager);
    let (pack_tx, mut pack_rx) = tokio::sync::mpsc::channel::<cerberus_proxy::api::PackCommand>(8);
    let packs_worker_manager = pack_worker_manager.clone();
    let engine_control_worker = engine_control.clone();
    let policy_source = shared_config.clone();
    let audit_key_for_worker = audit_key.clone();
    tokio::spawn(async move {
        use cerberus_proxy::api::PackCommand;
        // The SAME installation key follows hot-reloads (R9-16/F5.2): pack
        // snapshots are compiled keyed exactly like the boot engine.
        let payload_secret = Some(audit_key_for_worker.clone());
        while let Some(cmd) = pack_rx.recv().await {
            // Each arm produces (reply, Result) and the send happens once.
            let outcome: (
                tokio::sync::oneshot::Sender<Result<String, String>>,
                Result<String, String>,
            ) = match cmd {
                PackCommand::Install { request, reply } => {
                    // Pro gate (consistency with CLI): packs require Pro tier.
                    let license = load_license(Some(&license_path()));
                    let res = if let Err(e) = require_pro_for_pack_ops(&license) {
                        Err(format!("pack install aborted via control plane: {e}"))
                    } else {
                        let origin = request.origin_label().to_string();
                        match request.signed_pack() {
                            Ok(signed) => match packs_worker_manager.install(signed).await {
                                Ok(()) => match packs_worker_manager.snapshot_engine(payload_secret.as_deref()).await {
                                    Ok(new_engine) => {
                                        // Atomic rebase (synchronous helper, no await →
                                        // the std guard never crosses the `await` Send):
                                        // the pack's rules become the BASE and the
                                        // operator's policy is re-applied on top, so
                                        // an install does not wipe the custom rules or
                                        // overrides (fix review v6.1).
                                        match rebase_live_engine(&engine_control_worker, &policy_source, &new_engine) {
                                            Ok(rules) => {
                                                tracing::info!(pack_origin = %origin, rules, "pack installed via control plane");
                                                Ok(format!("pack installed (hot-reload): engine now has {rules} rules"))
                                            }
                                            Err(e) => Err(format!("policy rebase failed after install: {e}")),
                                        }
                                    }
                                    Err(e) => Err(format!("snapshot engine failed: {e}")),
                                },
                                Err(e) => Err(e),
                            },
                            Err(e) => Err(e.to_string()),
                        }
                    };
                    (reply, res)
                }
                PackCommand::Rollback { reply } => {
                    // Pro gate (finding v6): rollback reactivates a pack
                    // version — a Pro benefit, same as install. Denied in Free.
                    let license = load_license(Some(&license_path()));
                    let res = match require_pro_for_pack_ops(&license) {
                        Err(e) => Err(format!("pack rollback aborted via control plane: {e}")),
                        Ok(()) => match packs_worker_manager.rollback().await {
                            Ok(()) => match packs_worker_manager.snapshot_engine(payload_secret.as_deref()).await {
                                Ok(new_engine) => {
                                    // Same as install: the operator's policy is
                                    // re-applied over the reverted rules.
                                    match rebase_live_engine(&engine_control_worker, &policy_source, &new_engine) {
                                        Ok(rules) => {
                                            Ok(format!("rollback executed (hot-reload): engine now has {rules} rules"))
                                        }
                                        Err(e) => Err(format!("policy rebase failed after rollback: {e}")),
                                    }
                                }
                                Err(e) => Err(format!("snapshot engine failed: {e}")),
                            },
                            Err(e) => Err(e),
                        },
                    };
                    (reply, res)
                }
                PackCommand::List { reply } => {
                    let packs = packs_worker_manager.list_packs().await;
                    let res = Ok(format!("{} packs installed", packs.len()));
                    (reply, res)
                }
            };
            let _ = outcome.0.send(outcome.1);
        }
    });

    let ctx = Arc::new(ProxyContext {
        config: shared_config.clone(),
        engine: live_engine.clone(),
        redact_options: cerberus_engine::redact::RedactOptions::default(),
        api: ApiContext::with_store_opt(shared_config, store_opt.clone())
            .with_config_path(config_file())
            .with_pack_worker(pack_tx)
            .with_engine(engine_control)
            .with_audit_hash_key(audit_key.clone()),
        last_upstream: Arc::new(std::sync::Mutex::new(None)),
    });

    // F4 (dev feedback): the daemon watches the in-memory event buffer of
    // the control plane (`ApiContext.events`) and emits one-to-one feedback
    // for each intervention (block/redact/warn) that is logged. The buffer's
    // Arc is captured HERE, before moving `ctx` to the proxies.
    let api_events = ctx.api.events.clone();
    let mut interventions = crate::feedback_ux::InterventionWatcher::new();

    let addr: std::net::SocketAddr = config.listen.parse().map_err(|e| format!("invalid address: {e}"))?;
    let (actual, proxy_handle) = spawn_managed_proxy(addr, ctx.clone())
        .await
        .map_err(|e| format!("proxy error: {e}"))?;
    let mut forward_handle = if let Some(mitm_config) = mitm_config {
        match spawn_forward_proxy(mitm_config, ctx.clone()).await {
            Ok((forward_addr, handle)) => {
                println!("Cerberus MITM opt-in running on {forward_addr} (CONNECT exact allowlist)");
                Some(handle)
            }
            Err(error) => {
                let _ = proxy_handle.shutdown(Duration::from_secs(1)).await;
                return Err(format!("MITM opt-in proxy error: {error}"));
            }
        }
    } else {
        println!("MITM: disabled (default); reverse proxy only");
        None
    };

    // Write PID
    let pid = std::process::id();
    fs::write(pid_path(), pid.to_string()).map_err(|e| format!("cannot write PID: {e}"))?;
    if let Err(e) = persist_endpoint(actual, pid) {
        remove_runtime_files();
        if let Some(handle) = forward_handle.take() {
            let _ = handle.shutdown(Duration::from_secs(1)).await;
        }
        let _ = proxy_handle.shutdown(Duration::from_secs(1)).await;
        return Err(e);
    }

    println!("Cerberus proxy running on {actual}");
    println!("Cerberus started on {actual} (waiting for stop signals)");

    // ─── G) Graceful loop: Ctrl+C / SIGTERM / pid file removed → flush+close.
    // The signal future is resolved OUTSIDE the `tokio::select!` (the macro
    // does not accept `#[cfg]` in arms; on non-unix the SIGTERM arm is
    // `pending()`).
    #[cfg(unix)]
    let mut term_signal = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
        .map_err(|e| format!("cannot install SIGTERM handler: {e}"))?;
    let ctrl_c = tokio::signal::ctrl_c();
    #[cfg(unix)]
    let sigterm = term_signal.recv();
    #[cfg(not(unix))]
    let sigterm = std::future::pending::<Option<()>>();
    tokio::pin!(ctrl_c);
    tokio::pin!(sigterm);

    // F4 (dev feedback): each tick (1 s), drain new interventions →
    // desktop notification (rate 1/sec) + CLI line as fallback.
    let shutdown: bool = loop {
        tokio::select! {
            _ = &mut ctrl_c => {
                println!("stop signal (SIGINT) received");
                break true;
            }
            _ = &mut sigterm => {
                println!("stop signal (SIGTERM) received");
                break true;
            }
            () = tokio::time::sleep(Duration::from_secs(1)) => {
                if !is_running() {
                    println!("pid file removed — external stop requested");
                    break true;
                }
                // Each tick (1 s), drain new interventions → desktop
                // notification (rate 1/sec) + CLI line as fallback.
                crate::feedback_ux::emit_interventions(&api_events, &mut interventions).await;
            }
        }
    };
    let _ = shutdown;

    // First we close admission and drain requests: no handler can enqueue
    // audit after the store barrier.
    if let Some(handle) = forward_handle {
        if let Err(e) = handle.shutdown(Duration::from_secs(5)).await {
            eprintln!("MITM forward proxy: forced close during shutdown: {e}");
        } else {
            println!("MITM forward proxy: admission closed and tunnels drained");
        }
    }
    if let Err(e) = proxy_handle.shutdown(Duration::from_secs(5)).await {
        eprintln!("proxy: forced close during shutdown: {e}");
    } else {
        println!("proxy: admission closed and requests drained");
    }

    // After the signal: durable flush of the audit store (B) before dying.

    // After the stop signal: durable flush of the audit store (B).
    // If a flush fails, the daemon does NOT announce success (fix review v5
    // #4): audit loss is reported as an error, not as a clean shutdown.
    if let Some(store) = store_opt {
        store.begin_closing();
        match store.flush_durable().await {
            Ok(()) => println!("audit store: durable flush completed"),
            Err(e) => {
                eprintln!("audit store: flush error on shutdown: {e}");
                remove_runtime_files();
                return Err(format!("Cerberus stopped with audit error: {e}"));
            }
        }
        match store.close().await {
            Ok(()) => println!("audit store: writer closed"),
            Err(e) => {
                eprintln!("audit store: close error: {e}");
                remove_runtime_files();
                return Err(format!("Cerberus stopped with audit close error: {e}"));
            }
        }
    }
    remove_runtime_files();
    println!("Cerberus stopped (graceful)");
    Ok("Cerberus stopped (graceful, mutation flushed)".to_string())
}

// ─── `cerberus pack` commands (F7: install/list/rollback) ───────────────────

/// `cerberus pack install <signed.json>` — verifies the signature against
/// `CERBERUS_PACK_TRUST_ROOT` and merges the rules into the active engine.
/// Gated by license: packs require Pro tier (open-core).
///
/// # Errors
///
/// Error if the license is not Pro, the pack is invalid, there is no trust
/// root, or the rules do not compile.
pub(crate) async fn pack_install(pack_file: &str) -> Result<String, String> {
    let license = load_license(Some(&license_path()));
    require_pro_for_pack_ops(&license).map_err(|e| format!("pack install aborted: {e}"))?;
    let (audit_key, _) = resolve_audit_key();
    let packs = open_packs_manager(&audit_key)?;
    if let Some(root) = env_nonempty("CERBERUS_PACK_TRUST_ROOT") {
        // Rehydrate what is installed (engine history) before adding the new one.
        packs.load_installed_from_dir(&root).await?;
    }
    let before = packs.engine().lock().await.num_rules();
    let signed = PackManager::load_pack_from_file(pack_file)?;
    // `install` requires CERBERUS_PACK_TRUST_ROOT (fail-closed if missing).
    packs.install(signed).await?;
    let after = packs.engine().lock().await.num_rules();
    Ok(format!("pack installed: engine rules {before} → {after}"))
}

/// `cerberus pack list` — lists the signed packs present in
/// `~/.cerberus/packs` and their verification status against the trust root.
///
/// # Errors
///
/// Returns an error only if the directory cannot be read.
pub(crate) fn pack_list() -> Result<String, String> {
    let (audit_key, _) = resolve_audit_key();
    let _ = open_packs_manager(&audit_key)?; // ensures the packs layout (or fails fast).
    let dir = packs_dir();
    let mut entries = Vec::new();
    for entry in fs::read_dir(&dir).map_err(|e| format!("cannot read packs dir {}: {e}", dir.display()))? {
        let path = entry.map_err(|e| e.to_string())?.path();
        if path.extension().is_some_and(|e| e == "json") {
            entries.push(path);
        }
    }
    if entries.is_empty() {
        return Ok("no rule packs found in ~/.cerberus/packs.".to_string());
    }
    entries.sort();
    let root = env_nonempty("CERBERUS_PACK_TRUST_ROOT");
    let mut out = String::from("Rule packs:\n");
    for path in entries {
        let name = match PackManager::load_pack_from_file(&path) {
            Ok(signed) => {
                let verified = root
                    .as_deref()
                    .is_some_and(|r| signed.verify_with_trusted_root(r).is_ok());
                let pack = root.as_deref().and_then(|r| signed.extract_with_root(r).ok());
                let label = pack.map_or_else(
                    || name_from_path(&path),
                    |p| format!("{} v{}", p.metadata.name, p.metadata.version),
                );
                match (root.is_some(), verified) {
                    (true, true) => format!("  {label} ✓ valid signature"),
                    (true, false) => format!("  {label} ✗ invalid signature (rejected at boot)"),
                    (false, _) => format!("  {label} unverified (missing CERBERUS_PACK_TRUST_ROOT)"),
                }
            }
            Err(e) => format!("  {} (invalid: {e})", name_from_path(&path)),
        };
        out.push_str(&name);
        out.push('\n');
    }
    Ok(out)
}

/// Pro gate for rule pack operations (finding v6): install and rollback
/// mutate the active engine (Pro benefit). list is read-only and stays free.
fn require_pro_for_pack_ops(license: &LicenseManager) -> Result<(), String> {
    if license.is_pro() {
        Ok(())
    } else {
        Err("rule packs require a Pro license (open-core). Visit 'cerberus license'.".to_string())
    }
}

/// Rebase the proxy's active engine at runtime (hot-reload, fix review v5 +
/// v6.1): the rules of `new_engine` (defaults + packs) become the BASE and
/// the operator's persisted policy (categories, overrides, and custom rules)
/// is re-applied on top.
///
/// **Synchronous** helper on purpose: the std `RwLock` guard never crosses an
/// `await` (the worker future must remain `Send`).
///
/// Returns the number of rules of the newly activated engine.
fn rebase_live_engine(
    control: &cerberus_proxy::detection_policy::EngineControl,
    policy_source: &RwLock<ProxyConfig>,
    new_engine: &CompiledEngine,
) -> Result<usize, String> {
    // Holding the read-lock until the rebase finishes serializes this
    // publication with `commit_policy`, which holds the write-lock during
    // compile → persist → publish. If we cloned the policy and released the
    // lock earlier, a concurrent PUT could publish old-base/new-policy
    // and then this worker overwrite it with new-base/old-policy.
    let cfg = policy_source.read().unwrap_or_else(std::sync::PoisonError::into_inner);
    control.rebase(new_engine.rules().to_vec(), &cfg.policy)
}

/// Name (without extension) of a pack file for `pack list`.
fn name_from_path(path: &std::path::Path) -> String {
    path.file_name().and_then(|s| s.to_str()).map_or_else(
        || path.display().to_string(),
        |s| s.trim_end_matches(".json").to_string(),
    )
}

/// `cerberus pack rollback` — reverts to the previous engine (last install).
///
/// # Errors
///
/// Returns an error if there is no engine history to revert.
pub(crate) async fn pack_rollback() -> Result<String, String> {
    // Pro gate (finding v6): rollback reactivates a pack version, a Pro
    // benefit also in local mode without daemon (open-core).
    let license = load_license(Some(&license_path()));
    require_pro_for_pack_ops(&license).map_err(|e| format!("pack rollback aborted: {e}"))?;
    let (audit_key, _) = resolve_audit_key();
    let packs = open_packs_manager(&audit_key)?;
    if let Some(root) = env_nonempty("CERBERUS_PACK_TRUST_ROOT") {
        packs.load_installed_from_dir(&root).await?;
    }
    packs.rollback().await?;
    let rules = packs.engine().lock().await.num_rules();
    Ok(format!("pack rollback executed: engine rules {rules}"))
}

/// Stop the daemon (F4 cross-platform): delegates to
/// `platform::stop_process_graceful` — on unix it sends **SIGTERM** (not
/// SIGKILL) so the daemon does the graceful flush+close and force-kills only
/// if the process does not exit in ~5s; on windows `taskkill` without `/F`
/// first and `/F` as fallback. On all 3 platforms it cleans the pid file and
/// the endpoint file.
///
/// # Errors
///
/// Returns an error if there is no PID file or the process cannot be killed.
pub(crate) fn stop() -> Result<String, String> {
    let pid_path = pid_path();
    if !pid_path.exists() {
        return Err("Cerberus is not running (no PID file).".to_string());
    }

    let pid_str = fs::read_to_string(&pid_path).map_err(|e| format!("cannot read PID: {e}"))?;
    let pid: u32 = pid_str.trim().parse().map_err(|e| format!("invalid PID: {e}"))?;

    // Centralized in `platform` (a single cross-platform binary): on unix
    // SIGTERM → wait ≤5s → SIGKILL; on windows taskkill without /F → wait
    // ≤5s → taskkill /F. Shared shutdown loop, not duplicated.
    platform::stop_process_graceful(pid)?;

    remove_runtime_files();
    Ok(format!("Cerberus stopped (PID {pid})."))
}

/// Is the process with `pid` still alive? (delegated to
/// `platform::process_alive`: `kill -0` on unix,
/// `tasklist /FI "PID eq N"` on Windows).
fn process_alive(pid: u32) -> bool {
    platform::process_alive(pid)
}

/// Show the daemon status.
#[must_use]
pub(crate) fn status() -> String {
    if !pid_path().exists() {
        return format!("Cerberus: {}", console_style("STOPPED", "red"));
    }
    let pid_str = fs::read_to_string(pid_path()).unwrap_or_default();
    let pid = pid_str.trim();

    if is_running() {
        format!("Cerberus: {} (PID {})", console_style("RUNNING", "green"), pid)
    } else {
        remove_runtime_files();
        format!("Cerberus: {} (PID {pid} stale)", console_style("STOPPED", "red"))
    }
}

/// Is the daemon running? (pid file + live process).
pub(crate) fn is_running() -> bool {
    let pid_path = pid_path();
    if !pid_path.exists() {
        return false;
    }
    let Ok(pid_str) = fs::read_to_string(&pid_path) else {
        return false;
    };
    let Ok(pid) = pid_str.trim().parse::<u32>() else {
        return false;
    };
    process_alive(pid)
}

/// Apply console style (basic ANSI).
fn console_style(text: &str, color: &str) -> String {
    match color {
        "green" => format!("\x1b[32m{text}\x1b[0m"),
        "red" => format!("\x1b[31m{text}\x1b[0m"),
        "yellow" => format!("\x1b[33m{text}\x1b[0m"),
        _ => text.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Guard to serialize tests that mutate `std::env` (process-global).
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn require_pro_gate_for_pack_ops() {
        use ed25519_dalek::Signer;
        use serde_json::json;

        let free = LicenseManager::free();
        assert!(
            require_pro_for_pack_ops(&free).is_err(),
            "Free tier must deny pack operations (Pro-only)"
        );

        // Build a signed Pro license in a temp dir and load it.
        let dir = std::env::temp_dir().join(format!(
            "cerb_pro_gate_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map_or(0, |d| d.as_nanos())
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let keypair = ed25519_dalek::SigningKey::from_bytes(&[13u8; 32]);
        let license = json!({
            "tier": "pro",
            "email": "t@t.dev",
            "license_id": "t",
            "expires_at": null,
            "features": [],
        });
        let license_json = license.to_string();
        let signature = keypair.sign(license_json.as_bytes());
        let signed = cerberus_packs::license::SignedLicense {
            license_json,
            signature_hex: hex::encode(signature.to_bytes().as_slice()),
            signer_public_key_hex: hex::encode(keypair.verifying_key().as_bytes()),
            owner_public_key_hex: None,
        };
        let path = dir.join("license.json");
        std::fs::write(&path, serde_json::to_string(&signed).unwrap()).unwrap();
        let pro = LicenseManager::from_file_with_root(&path, &hex::encode(keypair.verifying_key().as_bytes()))
            .expect("pro license loads");
        assert!(
            require_pro_for_pack_ops(&pro).is_ok(),
            "Pro tier must allow pack operations"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    fn clear_env() {
        for var in [
            "CERBERUS_LISTEN_HOST",
            "CERBERUS_MODE",
            "CERBERUS_UPSTREAMS",
            "CERBERUS_UPSTREAM_URL",
            "CERBERUS_ADMIN_TOKEN",
            "CERBERUS_RETENTION_DAYS",
            "CERBERUS_LICENSE_PUBLIC_KEY",
            "CERBERUS_LICENSE_PATH",
        ] {
            std::env::remove_var(var);
        }
    }

    #[test]
    fn config_dir_is_dot_cerberus() {
        // config_dir() reads HOME/CERBERUS_CONFIG; acquire ENV_LOCK so a
        // parallel test that mutates HOME can't race this assertion.
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let dir = config_dir();
        #[cfg(not(windows))]
        assert!(dir.to_string_lossy().contains(".cerberus"));
        #[cfg(windows)]
        assert!(dir.to_string_lossy().to_uppercase().contains("CERBERUS"));
    }

    #[test]
    fn pid_path_is_in_config_dir() {
        // pid_path() derives from config_dir() which reads HOME; same guard.
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let path = pid_path();
        assert_eq!(path, config_dir().join("cerberus.pid"));
        assert!(path.to_string_lossy().ends_with("cerberus.pid"));
    }

    #[test]
    fn console_style_adds_ansi() {
        let styled = console_style("test", "green");
        assert!(styled.contains("32m"));
        assert!(styled.contains("0m"));
    }

    #[test]
    fn load_proxy_config_none_when_no_file() {
        let dir = tempfile::tempdir().expect("create isolated config dir");
        let missing = dir.path().join("config.yaml");

        assert!(load_proxy_config_from(&missing).is_none());
    }

    #[test]
    fn load_proxy_config_reads_explicit_file() {
        let dir = tempfile::tempdir().expect("create isolated config dir");
        let config = dir.path().join("config.yaml");
        std::fs::write(&config, "mode: shadow\n").expect("write isolated config");

        let loaded = load_proxy_config_from(&config).expect("load isolated config");
        assert_eq!(loaded.mode, OperationMode::Shadow);
    }

    #[test]
    fn process_alive_for_current_process() {
        assert!(process_alive(std::process::id()));
    }

    // ─── R9-16 (F5.2): the product engine is ALWAYS keyed ──────────────────

    #[test]
    fn product_engine_wiring_hashes_every_finding_with_hmac() {
        // The daemon's single engine-construction path must never emit an
        // unsalted hash: build_base_engine takes the installation key and
        // wires it unconditionally.
        let engine = build_base_engine(b"wiring-test-key").expect("build base engine");
        let out = engine.scan("my openai api key is sk-abcDEFghijklmnopqrstuvwxyz1234");
        assert!(!out.findings.is_empty(), "the probe text must produce findings");
        for finding in &out.findings {
            assert!(
                finding.hashed_value.starts_with("hmac:"),
                "product wiring must key EVERY hash, got {}",
                finding.hashed_value
            );
        }
        // Deterministic under the same key, divergent under another.
        let other = build_base_engine(b"other-key").expect("build other engine");
        let a = out.findings[0].hashed_value.clone();
        let b = other
            .scan("my openai api key is sk-abcDEFghijklmnopqrstuvwxyz1234")
            .findings[0]
            .hashed_value
            .clone();
        assert_ne!(a, b, "different installation keys must diverge");
    }

    #[test]
    fn packs_dir_is_under_config_dir() {
        assert_eq!(packs_dir(), config_dir().join("packs"));
    }

    // ─── Fix review v4, finding 5: real merge of config.yaml ───────────────

    #[test]
    fn resolve_config_preserves_yaml_fields() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let yaml = concat!(
            "listen: 127.0.0.1:9999\n",
            "mode: shadow\n",
            "fail_policy: open\n",
            "health_path: /custom-health\n",
            "max_body_bytes: 4096\n",
            "upstreams:\n",
            "  anthropic:\n",
            "    url: https://api.anthropic.com\n",
            "  openai:\n",
            "    url: https://api.openai.com\n",
        );
        let file_cfg = ProxyConfig::parse(yaml).expect("parse yaml");
        let cfg = resolve_config(8787, Some(file_cfg)).expect("resolve");

        // YAML fields that USED TO be lost with `..default()`:
        assert_eq!(cfg.mode, OperationMode::Shadow);
        assert_eq!(cfg.fail_policy, cerberus_proxy::config::FailPolicy::Open);
        assert_eq!(cfg.health_path, "/custom-health");
        assert_eq!(cfg.max_body_bytes, Some(4096));

        // Listen: file host + CLI port.
        assert_eq!(cfg.listen, "127.0.0.1:8787");
        // Upstreams from YAML preserved.
        assert_eq!(cfg.upstreams.len(), 2);
        // No token env → the YAML does not inject a token.
        assert!(cfg.admin_token.is_none());
        clear_env();
    }

    #[test]
    fn resolve_config_env_overrides_mode_host_upstreams_token() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();

        std::env::set_var("CERBERUS_LISTEN_HOST", "0.0.0.0");
        std::env::set_var("CERBERUS_MODE", "enforce");
        std::env::set_var("CERBERUS_UPSTREAM_URL", "https://api.example.com");
        std::env::set_var("CERBERUS_ADMIN_TOKEN", "s3cr3t-admin-token-1234567890");

        let cfg = resolve_config(9000, None).expect("resolve");
        assert_eq!(cfg.listen, "0.0.0.0:9000");
        assert_eq!(cfg.mode, OperationMode::Enforce);
        assert_eq!(cfg.admin_token.as_deref(), Some("s3cr3t-admin-token-1234567890"));
        // URL base → 3 upstreams (openai/anthropic/default).
        assert!(cfg.upstreams.contains_key("openai"));
        assert!(cfg.upstreams.contains_key("anthropic"));
        assert!(cfg.upstreams.contains_key("default"));
        clear_env();
    }

    #[test]
    fn resolve_config_errors_without_upstreams() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let err = resolve_config(8787, None).expect_err("must fail");
        assert!(err.contains("upstreams"), "got: {err}");
        clear_env();
    }

    #[test]
    fn retention_days_default_and_env() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        assert_eq!(retention_days_from_env(), 90);
        std::env::set_var("CERBERUS_RETENTION_DAYS", "30");
        assert_eq!(retention_days_from_env(), 30);
        std::env::set_var("CERBERUS_RETENTION_DAYS", "garbage");
        assert_eq!(retention_days_from_env(), 90);
        clear_env();
    }

    // ─── F7 in the product: licensing + packs (code review item 12) ────────

    fn test_keypair() -> ed25519_dalek::SigningKey {
        ed25519_dalek::SigningKey::from_bytes(&[7u8; 32])
    }

    /// Sign a Pro license in `dir/license.json` and return (path, root hex).
    fn write_signed_pro_license(dir: &std::path::Path) -> (PathBuf, String) {
        use ed25519_dalek::Signer;

        let license = cerberus_packs::license::License {
            tier: cerberus_packs::license::LicenseTier::Pro,
            email: "dev@cerberus.dev".to_string(),
            license_id: "f7-integration".to_string(),
            expires_at: None,
            features: Vec::new(),
        };
        let license_json = serde_json::to_string(&license).expect("serialize license");
        let keypair = test_keypair();
        let signature = keypair.sign(license_json.as_bytes());
        let signed = cerberus_packs::license::SignedLicense {
            license_json,
            signature_hex: hex::encode(signature.to_bytes().as_slice()),
            signer_public_key_hex: hex::encode(keypair.verifying_key().as_bytes()),
            owner_public_key_hex: None,
        };
        let path = dir.join("license.json");
        std::fs::write(&path, serde_json::to_string(&signed).expect("serialize signed license"))
            .expect("write license");
        (path, hex::encode(keypair.verifying_key().as_bytes()))
    }

    /// Unique temp directory (std only, no extra dep).
    fn temp_dir(prefix: &str) -> PathBuf {
        let mut d = std::env::temp_dir().join(format!(
            "cerberus_{prefix}_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map_or(0, |d| d.as_nanos())
        ));
        std::fs::create_dir_all(&d).expect("create temp dir");
        d = d.canonicalize().unwrap_or(d);
        d
    }

    #[test]
    fn license_wired_from_signed_file_at_boot() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let dir = temp_dir("license_wired");
        let (license_file, root_hex) = write_signed_pro_license(&dir);

        // Boot like the daemon: path via CERBERUS_LICENSE_PATH + trust root
        // via CERBERUS_LICENSE_PUBLIC_KEY → the Pro license activates.
        std::env::set_var("CERBERUS_LICENSE_PUBLIC_KEY", &root_hex);
        std::env::set_var("CERBERUS_LICENSE_PATH", &license_file);
        assert_eq!(license_path(), license_file);

        let mgr = load_license(Some(license_file.as_path()));
        assert!(mgr.is_pro(), "F7: signed license must activate Pro tier in the daemon");
        assert!(
            license_summary(&mgr).contains("tier=pro"),
            "boot log must include tier=pro: {}",
            license_summary(&mgr)
        );

        // Fail-open: signature not verifiable (no trust root) → Free, no panic.
        std::env::remove_var("CERBERUS_LICENSE_PUBLIC_KEY");
        let fallback = load_license(Some(license_file.as_path()));
        assert!(
            !fallback.is_pro(),
            "without trust root the daemon must fall back to Free (fail-open)"
        );
        assert!(license_summary(&fallback).contains("tier=free"));

        // Missing file → Free.
        let missing = dir.join("nope.json");
        assert!(!load_license(Some(&missing)).is_pro());

        std::env::remove_var("CERBERUS_LICENSE_PUBLIC_KEY");
        std::env::remove_var("CERBERUS_LICENSE_PATH");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn license_without_file_falls_back_to_free() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_env();
        let missing = std::env::temp_dir().join("cerberus-absent-license.json");
        let mgr = load_license(Some(&missing));
        assert_eq!(mgr.tier(), cerberus_packs::license::LicenseTier::Free);
        assert!(license_summary(&mgr).contains("tier=free"));
    }
}
